[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"

# We need openssl to be statically linked on windows to avoid madness,
# and openssl-src does that based on the crt-static feature being
# enabled for the target, so let's turn that on here.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
sccache = true

[build]
rustc-wrapper = "sccache"

[env]
SCCACHE_CACHE_SIZE = "15G"
SCCACHE_DIR = "${CARGO_HOME}/../sccache-cache"
