name: nightly-docs

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Install tools
        run: |
          cargo install mdbook || true
          sudo apt-get update && sudo apt-get install -y doxygen graphviz
      - name: Build mdBook
        run: mdbook build docs
      - name: Generate Doxygen
        run: doxygen Doxyfile.rust
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-artifacts
          path: |
            docs/book
            docs/doxygen/html
            docs/doxygen/wezterm.tag
