name: pre-commit

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - name: Install supporting tools
        run: |
          pip install pre-commit
          cargo install cargo-deny || true
          cargo install mdbook || true
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit (all files)
        run: pre-commit run --all-files --show-diff-on-failure
